// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlboybsrugdqrcdtszhc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsYm95YnNydWdkcXJjZHRzemhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NzI5OTcsImV4cCI6MjA2NjI0ODk5N30.5pbH1BJ6HL32EsxiWNMBa_FLum0payxPdeOKghMWRcQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);